name: mechanic_part
description: "Car and spare parts marketplace app"
publish_to: 'none'

version: 1.2.7+7

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.0
  go_router: ^14.6.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^17.2.3
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  purchases_flutter: ^9.7.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

flutter_native_splash:
  color: "#1E3A8A"
  image: assets/images/logo_new.png
  color_dark: "#1E3A8A"
  image_dark: assets/images/logo_new.png
  android_12:
    image: assets/images/logo_new.png
    color: "#1E3A8A"
    image_dark: assets/images/logo_new.png
    color_dark: "#1E3A8A"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

