name: mechanic_part
description: "Car and spare parts marketplace app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.0
  go_router: ^14.6.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^17.2.3
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  purchases_flutter: ^9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
    image_dark: assets/images/logo.png
    color_dark: "#FFFFFF"

